//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Circles = new HashSet<Circle>();
            this.Divisions = new HashSet<Division>();
            this.Regions = new HashSet<Region>();
            this.Sites = new HashSet<Site>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string TalukMandal { get; set; }
        public int DistrictId { get; set; }
        public string Landmark { get; set; }
        public string ContactPersonNumber { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactEMail { get; set; }
        public decimal Latitute { get; set; }
        public decimal Longitute { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Circle> Circles { get; set; }
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
