//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELMAS_UPS_V1Entities : DbContext
    {
        public ELMAS_UPS_V1Entities()
            : base("name=ELMAS_UPS_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessControl> AccessControls { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AlaramType> AlaramTypes { get; set; }
        public virtual DbSet<AlarmStatu> AlarmStatus { get; set; }
        public virtual DbSet<Circle> Circles { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DailySiteEvent> DailySiteEvents { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<EndClient> EndClients { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<LatestSiteEvent> LatestSiteEvents { get; set; }
        public virtual DbSet<MonthlySiteEvent> MonthlySiteEvents { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PortPurpose> PortPurposes { get; set; }
        public virtual DbSet<PrimeVendor> PrimeVendors { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<QuarterlySiteEvent> QuarterlySiteEvents { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteAlarmEvent> SiteAlarmEvents { get; set; }
        public virtual DbSet<SiteEvent> SiteEvents { get; set; }
        public virtual DbSet<SitePort> SitePorts { get; set; }
        public virtual DbSet<SiteRemoteAction> SiteRemoteActions { get; set; }
        public virtual DbSet<SiteRemoteActionHistory> SiteRemoteActionHistories { get; set; }
        public virtual DbSet<SiteRemoteActionType> SiteRemoteActionTypes { get; set; }
        public virtual DbSet<SiteStatu> SiteStatus { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TrackingHistory> TrackingHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccess> UserAccesses { get; set; }
        public virtual DbSet<UserProject> UserProjects { get; set; }
        public virtual DbSet<UserSite> UserSites { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<Usertbl> Usertbls { get; set; }
        public virtual DbSet<WeeklySiteEvent> WeeklySiteEvents { get; set; }
    }
}
