//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Sites = new HashSet<Site>();
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EndClientId { get; set; }
        public string AccessId { get; set; }
        public string AccessPassword { get; set; }
    
        public virtual EndClient EndClient { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
