//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteRemoteActionType
    {
        public SiteRemoteActionType()
        {
            this.SiteRemoteActions = new HashSet<SiteRemoteAction>();
            this.SiteRemoteActionHistories = new HashSet<SiteRemoteActionHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ActionId { get; set; }
    
        public virtual ICollection<SiteRemoteAction> SiteRemoteActions { get; set; }
        public virtual ICollection<SiteRemoteActionHistory> SiteRemoteActionHistories { get; set; }
    }
}
