//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAlarmEvent
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int SiteEventId { get; set; }
        public int AlaramTypeId { get; set; }
        public System.DateTime EventOccurred { get; set; }
        public System.DateTime EventResotred { get; set; }
        public int AlarmStatusId { get; set; }
    
        public virtual AlaramType AlaramType { get; set; }
        public virtual AlarmStatu AlarmStatu { get; set; }
        public virtual Site Site { get; set; }
        public virtual SiteEvent SiteEvent { get; set; }
    }
}
