//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.DailySiteEvents = new HashSet<DailySiteEvent>();
            this.LatestSiteEvents = new HashSet<LatestSiteEvent>();
            this.MonthlySiteEvents = new HashSet<MonthlySiteEvent>();
            this.QuarterlySiteEvents = new HashSet<QuarterlySiteEvent>();
            this.SiteAlarmEvents = new HashSet<SiteAlarmEvent>();
            this.SiteEvents = new HashSet<SiteEvent>();
            this.SitePorts = new HashSet<SitePort>();
            this.SiteRemoteActions = new HashSet<SiteRemoteAction>();
            this.SiteRemoteActionHistories = new HashSet<SiteRemoteActionHistory>();
            this.UserAccesses = new HashSet<UserAccess>();
            this.UserSites = new HashSet<UserSite>();
            this.WeeklySiteEvents = new HashSet<WeeklySiteEvent>();
        }
    
        public int Id { get; set; }
        public string SiteId { get; set; }
        public string Name { get; set; }
        public int AddressId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int StatusId { get; set; }
        public int ProjectId { get; set; }
        public string MobileNumber { get; set; }
        public string SIMNumber { get; set; }
        public string SIMNetworkDetails { get; set; }
        public string SIMAPNDetails { get; set; }
        public string IEMINumber { get; set; }
        public int DivisionId { get; set; }
        public string Description { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<DailySiteEvent> DailySiteEvents { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<LatestSiteEvent> LatestSiteEvents { get; set; }
        public virtual ICollection<MonthlySiteEvent> MonthlySiteEvents { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<QuarterlySiteEvent> QuarterlySiteEvents { get; set; }
        public virtual SiteStatu SiteStatu { get; set; }
        public virtual ICollection<SiteAlarmEvent> SiteAlarmEvents { get; set; }
        public virtual ICollection<SiteEvent> SiteEvents { get; set; }
        public virtual ICollection<SitePort> SitePorts { get; set; }
        public virtual ICollection<SiteRemoteAction> SiteRemoteActions { get; set; }
        public virtual ICollection<SiteRemoteActionHistory> SiteRemoteActionHistories { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
        public virtual ICollection<UserSite> UserSites { get; set; }
        public virtual ICollection<WeeklySiteEvent> WeeklySiteEvents { get; set; }
    }
}
