//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteRemoteActionHistory
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int ActionTypeId { get; set; }
        public string ActionValue { get; set; }
        public System.DateTime RegistationDateTime { get; set; }
        public System.DateTime ScheduleDateTime { get; set; }
        public System.DateTime SubmittedDateTime { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual SiteRemoteActionType SiteRemoteActionType { get; set; }
    }
}
