//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usertbl
    {
        public Usertbl()
        {
            this.UserProjects = new HashSet<UserProject>();
            this.UserSites = new HashSet<UserSite>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string MobilePhone { get; set; }
        public string Password { get; set; }
        public string MobilePassCode { get; set; }
        public int UserStatusId { get; set; }
    
        public virtual ICollection<UserProject> UserProjects { get; set; }
        public virtual ICollection<UserSite> UserSites { get; set; }
        public virtual UserStatu UserStatu { get; set; }
    }
}
