//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public int Address { get; set; }
        public string MobileNumber { get; set; }
        public string Emai { get; set; }
        public string AccessId { get; set; }
        public string AccessPassword { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
