//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DivisionId { get; set; }
        public int RegionId { get; set; }
        public int CircleId { get; set; }
        public int ProjectId { get; set; }
        public int SiteId { get; set; }
        public int AccessControlId { get; set; }
    
        public virtual AccessControl AccessControl { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual Project Project { get; set; }
        public virtual Region Region { get; set; }
        public virtual Site Site { get; set; }
        public virtual User User { get; set; }
    }
}
